
# Numpy Exercises
![alt text](https://i.morioh.com/b53d97587a.png)

`numpy` is one of the most essential libraries for Machine Learning and Deep Learning as it allows us to work with large, multi-dimensional arrays and matrices, and perform high-level mathematical functions on these arrays. 

**Import data and libraries**

In [1]:
import numpy as np

## Create numpy array

For each of this exercise, try different method to produce the output

In [8]:
# Create an 1D array / row vector 
# Expected output: [1 2 3 4 5 6]
# Print out the shape of the array

# Your code here


array([1, 2, 3, 4, 5, 6])

### ❓Question 1 (EXPRESSION) **Create an 2D array / matrix**

Write the expression of the 2D array of this matrix:

\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix}

Give your answer for the question below:

In [7]:
# Your code here


array([[1, 2, 3],
       [4, 5, 6]])

### ❓Question 2 (EXPRESSION)
Create an array of **all ones** with the shape (2, 5), it will look like:

```
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
```

*Hint*: Don't forget about dtype !

In [ ]:
# Your code here


** ❓Exploring** np.arange() and np.linspace(), Expected output:
```
array([5, 6, 7])
```

In [15]:
# Your code here


### ❓Question 3 (EXPRESSION)
Write the expression to create a RANGE of integer numbers from 1 to 20 **without listing them out manually** :

Expected output: 
```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
```

In [17]:
# Your code here


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

### ❓Question 4 (EXPRESSION)
Create an array of evenly spaced numbers in an interval by 2 methods:

Expected output:
```
[ 2.  4.  6.  8. 10.]
```

In [ ]:
# Create an array of evenly spaced numbers in an interval
# Expected output: [ 2.  4.  6.  8. 10.]

answer_1 = np.arange(____________)
print(f"Method 1: {answer_1}")

answer_2 = np.linspace(___________)
print(f"Method 2: {answer_2}")

Method 1: [ 2.  4.  6.  8. 10.]
Method 2: [ 2.  4.  6.  8. 10.]


### ❓Question 5 (EXPRESSION)

Can you used numpy to make an array of this matrix :

*Expected output*:
```
array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)
```


In [ ]:
# Your code here


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

## **Exploring**: np.random 

Take a look at np random library: https://numpy.org/doc/1.16/reference/routines.random.html


### ❓Question 6: Create 5 random integers between 2 and 40

*Sample random Expected output*
```
array([ 5, 29, 33,  4, 26])
```

In [ ]:
# Your code here


### ❓ Question 7: Create an array of random number. 

*Expected output:* An 3x3x3 array of random numbers

```
[[[ 0.5011419  -0.83992883 -1.56522768]
  [-1.03082136  0.72382357  0.41303015]
  [ 0.69578126 -0.80812391 -0.84152928]]

 [[-0.02096719 -0.4336578   0.79906133]
  [ 0.65931825 -0.22144085 -0.81873375]
  [-0.47665216  0.21219145  0.6083723 ]]

 [[-0.68824412  0.76540013  1.45334427]
  [-0.63239304 -0.03988415 -0.9619883 ]
  [ 0.57695348 -1.1679731   1.36471126]]]
```

In [ ]:
# Create an array of random number
# Expected output: An 3x3x3 array of random numbers

# Your code here


## Describing a matrix

In [3]:
a = np.array([ np.ones(5), np.ones(5) ])
b = np.array([ np.zeros(5), np.zeros(5) ])
c = np.array([ np.zeros(5), np.zeros(5) ])

r = np.array([a, b, c])
r

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### ❓Question 8: (CHOOSE CORRECT ANSWER)
What is the **shape** of r?

- A. (5, 3, 2)
- B. (3, 2, 5)
- C. (2, 3, 5)

In [4]:
# Your answer is:


(3, 2, 5)

### ❓ Question 9: (CHOOSE CORRECT ANSWER)
How many **number** of elements in r

- A. 15
- B. 20
- C. 30


In [19]:
# Your answer is:


### ❓ Question 10: (CHOOSE CORRECT ANSWER)
How many **dimensions** do r have?

- A. 3
- B. 5
- C. 2



In [ ]:
# Your answer is:


## Indexing

In [ ]:
e = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

In [ ]:
# Get the number 7 in array e using indexing
# Expected result: 7

# Your code here


In [ ]:
# Get the the first row of array e
# Expecte result: [1 2 3 4]

# Your code here


### **QUESTION 11**
>Given a 2D array `arr`, which of the following expressions returns the first column of `arr`?

<ol type='A'>
    <li><code>np.col(arr)[0]</code></li>
    <li><code>arr[:,0]</code></li>
    <li><code>arr[:][0]</code></li>
    <li><code>arr[0,:]</code></li>
</ol>

In [ ]:
# Your answer here


### **QUESTION 12**
>Given a 2D array `arr`, which of the following expressions returns the first and last columns of `arr`?
<ol type='A'>
    <li><code>np.columns(arr)[0,-1]</code></li>
    <li><code>arr[:,[0,1]]</code></li>
    <li><code>arr[:,-1]</code></li>
    <li><code>arr[:,[0,-1]]</code></li>
</ol>

In [ ]:
# Your answer here


### **QUESTION 13**
>Given a 2D array called `arr`, which of the following expressions returns the reverse of `arr`?
<ol type='A'>
    <li><code>arr[::-1, ::-1]</code></li>
    <li><code>arr[:-1, :-1]</code></li>
    <li><code>arr[0:-1:1, 0:-1:1]</code></li>
    <li><code>arr[0::-1,0::-1]</code></li>
</ol>

For example, if
$$
\begin{aligned}
    arr = &\left[
    \begin{bmatrix}
        1 & 2 & 3
    \end{bmatrix}\\
    \;\;
    \begin{bmatrix}
        4 & 5 & 6
    \end{bmatrix}\right]
\end{aligned}
$$
then the reverse of `arr` is
$$
\begin{aligned}
    arr_{reversed} = &\left[
    \begin{bmatrix}
        6 & 5 & 4
    \end{bmatrix}\\
    \;\;
    \begin{bmatrix}
        3 & 2 & 1
    \end{bmatrix}\right]
\end{aligned}
$$

In [6]:
# Check your answer here
a = np.array([[1, 2, 3], [4, 5, 6]])


## Boolean indexing

In [8]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
b

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# Get all the numbers that are more than 5.
# Expected: array([6, 7, 6])
# Your code here


In [11]:
# Get all the numbers that are more than 2 but less than 6.
# Expected: array([3, 4, 5, 5, 4, 3])
# Your code here


### **QUESTION 14**
>Write an ***expression*** that gives the same array as `b` EXCEPT all numbers greater than 5 is changed to 5 and other numbers stay the same. *(Hint: `np.where`)*

More specifically, we have:
$$
b=
\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 & 6 & 7 & 6 & 5 & 4 & 3 & 2 & 1
\end{bmatrix}
$$
so the solution should give
$$
\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 & 5 & 5 & 5 & 5 & 4 & 3 & 2 & 1
\end{bmatrix}
$$

In [ ]:
# Your code/answer here


### **QUESTION 15**
>Given an array `c` below, write an ***expression*** that gives an array of the *indices* of all non-zero numbers in `c`.

More specifically, we have:
$$
c =
\begin{bmatrix}
    0 & 10 & 11 & 0 & 0 & 12 & 0 & 13 & 14
\end{bmatrix}
$$
then the solution should give
$$
\begin{bmatrix}
    1 & 2 & 5 & 7 & 8
\end{bmatrix}
$$

In [13]:
c = np.array([0, 10, 11, 0, 0, 12, 0, 13, 14])

# Your code here


array([10, 11, 12, 13, 14])

## Transposing

### **QUESTION 16**

Given the following matrices, answer the question below.

$$
A = 
\begin{bmatrix}
    1 & 2 & 3 & 4\\
    5 & 6 & 7 & 8\\
    9 & 10 & 11 & 12
\end{bmatrix}\\
B = 
\begin{bmatrix}
    6 & 3 & 7 & 4\\
    6 & 9 & 2 & 6
\end{bmatrix}
$$

> Which of the following computations will give the matrix below? Select all that apply.
$$
\begin{bmatrix}
    49 & 54\\
    129 & 146\\
    209 & 238
\end{bmatrix}\\
$$
<ol type='A'>
    <li><code>np.matmul(B, A.T)</code></li>
    <li><code>np.dot(A, B.T)</code></li>
    <li><code>np.matmul(A.T, B)</code></li>
    <li><code>A @ B.T</code></li>
    <li><code>np.dot(A,B)</code></li>
    <li><code>B @ A.T</code></li>
    <li><code>np.matmul(A, B.T)</code></li>
</ol>

In [ ]:
# Your code/answer here


In [ ]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
b = np.array([[6, 3, 7, 4],
              [6, 9, 2, 6]])

# Given these 2 matrics, how do we arrive at the expected result?
# Expected result:[[ 49,  54],
#                  [129, 146],
#                  [209, 238]]
# Your code here



## Reshape array

In [14]:
# Reshape 2x3 maxtrix b to an 1x6 row vector
# Expected result: [[1 2 3 4 5 6]]
d = np.array([[1,2,3],
              [4,5,6]])

# Your code here


array([1, 2, 3, 4, 5, 6])

In [16]:
# Reshape this 1x6 row vector to an 6x1 column vector
d = np.array([[1, 2, 3, 4, 5, 6]])
# Expected result: [[1]
#                   [2]
#                   [3]
#                   [4]
#                   [5]
#                   [6]]

# Your code here


### **QUESTION 17**
>Write an ***expression*** which uses `.reshape(...)` to create a 3x3 matrix with the values ranging from 10 to 18.
$$
\begin{bmatrix}
    10 & 11 & 12\\
    13 & 14 & 15\\
    16 & 17 & 18
\end{bmatrix}\\
$$

In [ ]:
# Create a 3x3 matrix with the values ranging from 10 to 18
# Expected result: [[10, 11, 12],
#                   [13, 14, 15],
#                   [16, 17, 18]]
# Your code/answer here



### **QUESTION 18**
>Given an array `arr` of any shape, which of the following expressions returns a flattened version of `arr`? Select all that apply.
<ol type='A'>
    <li><code>arr.reshape(1,-1)</code></li>
    <li><code>arr.flatten()</code></li>
    <li><code>arr.reshape(-1)</code></li>
    <li><code>np.flatten(arr)</code></li>
    <li><code>arr.reshape(-1,1)</code></li>
</ol>

For example, if
$$
\begin{aligned}
    arr = &\left[
    \begin{bmatrix}
        1 & 2
    \end{bmatrix}\\
    \;
    \begin{bmatrix}
        3 & 4
    \end{bmatrix}\\
    \;\;
    \begin{bmatrix}
        5 & 6
    \end{bmatrix}\right]
\end{aligned}
$$
then a flattened `arr` is
$$
arr_{flat} =
\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

Note that the result is a 1D array, not a 2D array with one row.

In [ ]:
# Your code/answer here


## Aggregate functions

In [ ]:
s = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(s)

# Maximum number for the whole matrix
arr_max = ____ # fill in the blank
print("Max:", arr_max, sep = "\n")

# Minimum number for the whole matrix
arr_min = ____
print("Min:", arr_min, sep = "\n")

# Max element in each column
col_max = ____
print("Max in each column:", col_max, sep = "\n")

# Min element in each row
row_min = ____
print("Min in each row:", row_min, sep = "\n")


### **QUESTION 19**
>Given an array `arr` of any shape, which of the following expressions returns the mean of `arr`, assuming there's no error?
<ol type='A'>
    <li><code>np.mean(arr)</code></li>
    <li><code>arr.mean()</code></li>
    <li><code>arr.sum() / arr.size</code></li>
    <li>All of the above</li>
</ol>

In [ ]:
# Your code/answer here


### **QUESTION 20**
>Given an array `arr` of any shape, which of the following expressions returns the standard deviation of `arr`, assuming there's no error?
<ol type='A'>
    <li><code>arr.std()</code></li>
    <li><code>`arr.var()**(1/2)`</code></li>
    <li><code>`np.sqrt(np.var(arr))`</code></li>
    <li><code>`np.std(arr)`</code></li>
    <li><code>`np.sqrt((arr**2).mean() - arr.mean()**2)`</code></li>
    <li>All of the above</li>
 </ol>

In [ ]:
# Your code/answer here
