
# Numpy Exercises
![alt text](https://i.morioh.com/b53d97587a.png)

`numpy` is one of the most essential libraries for Machine Learning and Deep Learning as it allows us to work with large, multi-dimensional arrays and matrices, and perform high-level mathematical functions on these arrays. 

**Import data and libraries**

In [1]:
import numpy as np

## Create numpy array

For each of this exercise, try different method to produce the output

In [2]:
# Create an 1D array / row vector 
# Expected output: [1 2 3 4 5 6]
# Print out the shape of the array

answer_1 = np.array([1, 2, 3, 4, 5, 6])
print(f"Method 1: {answer_1}")

answer_2 = np.array([i for i in range(1, 7)])
print(f"Method 2: {answer_2}")

answer_3 = np.arange(1, 7) 
print(f"Method 3: {answer_3}")

Method 1: [1 2 3 4 5 6]
Method 2: [1 2 3 4 5 6]
Method 3: [1 2 3 4 5 6]


### ❓Question 1 (EXPRESSION) **Create an 2D array / matrix**

Write the expression of the 2D array of this matrix:

\begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6\\
\end{bmatrix}

Give your answer for the question below:

In [3]:
# Your code here
a2 = np.arange(1,7).reshape(2,3)
a2

array([[1, 2, 3],
       [4, 5, 6]])

### ❓Question 2 (EXPRESSION)
Create an array of **all ones** with the shape (2, 5), it will look like:

```
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
```

*Hint*: Don't forget about dtype !

In [4]:
# Your code here
answer = np.ones(shape = (2, 5), dtype = "float32")
answer

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

**❓Exploring** np.arange() and np.linspace(), Expected output:
```
array([5, 6, 7])
```

In [9]:
# Your code here
a_arange = np.arange(5, 8)
print('arange:', a_arange)

a_linspace = np.linspace(5, 7, 3, dtype='int')
print('linspace:', a_linspace)

arange: [5 6 7]
linspace: [5 6 7]


### ❓Question 3 (EXPRESSION)
Write the expression to create a RANGE of integer numbers from 1 to 20 **without listing them out manually** :

Expected output: 
```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
```

In [11]:
# Your code here
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### ❓Question 4 (EXPRESSION)
Create an array of evenly spaced numbers in an interval by 2 methods:

Expected output:
```
[ 2.  4.  6.  8. 10.]
```

In [13]:
# Create an array of evenly spaced numbers in an interval
# Expected output: [ 2.  4.  6.  8. 10.]

answer_1 = np.arange(2, 12, 2, dtype='float32')
print(f"Method 1: {answer_1}")

answer_2 = np.linspace(2, 10, 5)
print(f"Method 2: {answer_2}")

Method 1: [ 2.  4.  6.  8. 10.]
Method 2: [ 2.  4.  6.  8. 10.]


### ❓Question 5 (EXPRESSION)

Can you used numpy to make an array of this matrix :

*Expected output*:
```
array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)
```


In [15]:
# Your code here
a = np.ones((6, 6), dtype = 'float32')
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

## **Exploring**: np.random 

Take a look at np random library: https://numpy.org/doc/1.16/reference/routines.random.html


### ❓Question 6: Create 5 random integers between 2 and 40

*Sample random Expected output*
```
array([ 5, 29, 33,  4, 26])
```

In [16]:
# Your code here
answer = np.random.randint(2, 40, 5)
answer

array([20, 33, 15, 26, 16])

### ❓ Question 7: Create an array of random number. 

*Expected output:* An 3x3x3 array of random numbers from 0 to 1

```
array([[[0.86965301, 0.0890044 , 0.60675301],
        [0.90510118, 0.58106993, 0.57548918],
        [0.86641249, 0.1943134 , 0.97429073]],

       [[0.6128744 , 0.64924883, 0.88394359],
        [0.16109806, 0.10928149, 0.05348695],
        [0.72292245, 0.32174947, 0.74017052]],

       [[0.45247741, 0.46444955, 0.02558105],
        [0.3160687 , 0.48321255, 0.72373692],
        [0.48709164, 0.78892972, 0.88801418]]])
```

In [90]:
# Create an array of random number
# Expected output: An 3x3x3 array of random numbers

# Your code here
np.random.rand(3,3,3)

array([[[0.86965301, 0.0890044 , 0.60675301],
        [0.90510118, 0.58106993, 0.57548918],
        [0.86641249, 0.1943134 , 0.97429073]],

       [[0.6128744 , 0.64924883, 0.88394359],
        [0.16109806, 0.10928149, 0.05348695],
        [0.72292245, 0.32174947, 0.74017052]],

       [[0.45247741, 0.46444955, 0.02558105],
        [0.3160687 , 0.48321255, 0.72373692],
        [0.48709164, 0.78892972, 0.88801418]]])

## Describing a matrix

In [47]:
a = np.ones((2,5))
b = np.zeros((2,5))
c = np.zeros((2,5))

r = np.array([a, b, c])
r

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### ❓Question 8: (CHOOSE CORRECT ANSWER)
What is the **shape** of r?

- A. (5, 3, 2)
- B. (3, 2, 5)
- C. (2, 3, 5)

In [48]:
# Your answer is:
r.shape

(3, 2, 5)

### ❓ Question 9: (CHOOSE CORRECT ANSWER)
How many **number** of elements in r

- A. 15
- B. 20
- C. 30


In [49]:
# Your answer is:
r.size

30

### ❓ Question 10: (CHOOSE CORRECT ANSWER)
How many **dimensions** do r have?

- A. 3
- B. 5
- C. 2



In [50]:
# Your answer is:
r.ndim

3

## Indexing

In [53]:
e = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
# Get the number 7 in array e using indexing
# Expected result: 7

# Your code here
e[1, 2]

7

In [56]:
# Get the the first row of array e
# Expecte result: [1 2 3 4]

# Your code here
e[0]

array([1, 2, 3, 4])

### **QUESTION 11**
>Given a 2D array `arr`, which of the following expressions returns the first column of `arr`?

<ol type='A'>
    <li><code>np.col(arr)[0]</code></li>
    <li><code>arr[:,0]</code></li>
    <li><code>arr[:][0]</code></li>
    <li><code>arr[0,:]</code></li>
</ol>

In [ ]:
# Your answer here
# => B

### **QUESTION 12**
>Given a 2D array `arr`, which of the following expressions returns the first and last columns of `arr`?
<ol type='A'>
    <li><code>np.columns(arr)[0,-1]</code></li>
    <li><code>arr[:,[0,1]]</code></li>
    <li><code>arr[:,-1]</code></li>
    <li><code>arr[:,[0,-1]]</code></li>
</ol>

In [ ]:
# Your answer here
# => D

### **QUESTION 13**
>Given a 2D array called `arr`, which of the following expressions returns the reverse of `arr`?
<ol type='A'>
    <li><code>arr[::-1, ::-1]</code></li>
    <li><code>arr[:-1, :-1]</code></li>
    <li><code>arr[0:-1:1, 0:-1:1]</code></li>
    <li><code>arr[0::-1,0::-1]</code></li>
</ol>

For example, if
$$
\begin{aligned}
    arr = &\left[
    \begin{bmatrix}
        1 & 2 & 3
    \end{bmatrix}\\
    \;\;
    \begin{bmatrix}
        4 & 5 & 6
    \end{bmatrix}\right]
\end{aligned}
$$
then the reverse of `arr` is
$$
\begin{aligned}
    arr_{reversed} = &\left[
    \begin{bmatrix}
        6 & 5 & 4
    \end{bmatrix}\\
    \;\;
    \begin{bmatrix}
        3 & 2 & 1
    \end{bmatrix}\right]
\end{aligned}
$$

In [64]:
# Check your answer here
a = np.array([[1, 2, 3], [4, 5, 6]])
a[::-1, ::-1]


array([[6, 5, 4],
       [3, 2, 1]])

## Boolean indexing

In [67]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
b

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [68]:
# Get all the numbers that are more than 5.
# Expected: array([6, 7, 6])
# Your code here
b[b>5]

array([6, 7, 6])

In [69]:
# Get all the numbers that are more than 2 but less than 6.
# Expected: array([3, 4, 5, 5, 4, 3])
# Your code here
b[(b > 2) & (b < 6)]

array([3, 4, 5, 5, 4, 3])

### **QUESTION 14**
>Write an ***expression*** that gives the same array as `b` EXCEPT all numbers greater than 5 is changed to 5 and other numbers stay the same. *(Hint: `np.where`)*

More specifically, we have:
$$
b=
\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 & 6 & 7 & 6 & 5 & 4 & 3 & 2 & 1
\end{bmatrix}
$$
so the solution should give
$$
\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 & 5 & 5 & 5 & 5 & 4 & 3 & 2 & 1
\end{bmatrix}
$$

In [72]:
# Answer
np.where(b>5, 5, b)

array([1, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2, 1])

### **QUESTION 15**
>Given an array `c` below, write an ***expression*** that gives an array of the *indices* of all non-zero numbers in `c`.

More specifically, we have:
$$
c =
\begin{bmatrix}
    0 & 10 & 11 & 0 & 0 & 12 & 0 & 13 & 14
\end{bmatrix}
$$
then the solution should give
$$
\begin{bmatrix}
    1 & 2 & 5 & 7 & 8
\end{bmatrix}
$$

In [73]:
c = np.array([0, 10, 11, 0, 0, 12, 0, 13, 14])

# Your code here


## Transposing

### **QUESTION 16**

Given the following matrices, answer the question below.

$$
A = 
\begin{bmatrix}
    1 & 2 & 3 & 4\\
    5 & 6 & 7 & 8\\
    9 & 10 & 11 & 12
\end{bmatrix}\\
B = 
\begin{bmatrix}
    6 & 3 & 7 & 4\\
    6 & 9 & 2 & 6
\end{bmatrix}
$$

> Which of the following computations will give the matrix below? Select all that apply.
$$
\begin{bmatrix}
    49 & 54\\
    129 & 146\\
    209 & 238
\end{bmatrix}\\
$$
<ol type='A'>
    <li><code>np.matmul(B, A.T)</code></li>
    <li><code>np.dot(A, B.T)</code></li>
    <li><code>np.matmul(A.T, B)</code></li>
    <li><code>A @ B.T</code></li>
    <li><code>np.dot(A,B)</code></li>
    <li><code>B @ A.T</code></li>
    <li><code>np.matmul(A, B.T)</code></li>
</ol>

In [74]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
b = np.array([[6, 3, 7, 4],
              [6, 9, 2, 6]])

# Given these 2 matrics, how do we arrive at the expected result?
# Expected result:[[ 49,  54],
#                  [129, 146],
#                  [209, 238]]
# Answer:
b_transpose = b.T # switching from shape (2,4) to (4,2)
answer = a @ b_transpose # (3,4) @ (4,2) => (3,2)
answer

array([[ 49,  54],
       [129, 146],
       [209, 238]])


## Reshape array

In [76]:
# Reshape 2x3 maxtrix b to an 1x6 row vector
# Expected result: [[1 2 3 4 5 6]]
d = np.array([[1,2,3],
              [4,5,6]])

# Your code here
d.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [77]:
# Reshape this 1x6 row vector to an 6x1 column vector
d = np.array([[1, 2, 3, 4, 5, 6]])
# Expected result: [[1]
#                   [2]
#                   [3]
#                   [4]
#                   [5]
#                   [6]]

# Your code here
d.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### **QUESTION 17**
>Write an ***expression*** which uses `.reshape(...)` to create a 3x3 matrix with the values ranging from 10 to 18.
$$
\begin{bmatrix}
    10 & 11 & 12\\
    13 & 14 & 15\\
    16 & 17 & 18
\end{bmatrix}\\
$$

In [78]:
# Create a 3x3 matrix with the values ranging from 10 to 18
# Expected result: [[10, 11, 12],
#                   [13, 14, 15],
#                   [16, 17, 18]]
# Answer
answer = np.arange(10, 19).reshape(3, 3)
answer


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

### **QUESTION 18**
>Given an array `arr` of any shape, which of the following expressions returns a flattened version of `arr`? Select all that apply.
<ol type='A'>
    <li><code>arr.reshape(1,-1)</code></li>
    <li><code>arr.flatten()</code></li>
    <li><code>arr.reshape(-1)</code></li>
    <li><code>arr.flatten()</code></li>
    <li><code>arr.reshape(-1,1)</code></li>
</ol>

For example, if
$$
\begin{aligned}
    arr = &\left[
    \begin{bmatrix}
        1 & 2
    \end{bmatrix}\\
    \;
    \begin{bmatrix}
        3 & 4
    \end{bmatrix}\\
    \;\;
    \begin{bmatrix}
        5 & 6
    \end{bmatrix}\right]
\end{aligned}
$$
then a flattened `arr` is
$$
arr_{flat} =
\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

Note that the result is a 1D array, not a 2D array with one row.

In [86]:
# Answer: C & D
arr = np.arange(1, 7).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
# option 1:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [84]:
# Option 2:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

## Aggregate functions

In [87]:
s = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(s)

# Maximum number for the whole matrix
arr_max = s.max() # fill in the blank
print("Max:", arr_max, sep = "\n")

# Minimum number for the whole matrix
arr_min = s.min()
print("Min:", arr_min, sep = "\n")

# Max element in each column
col_max = s.max(axis = 0)
print("Max in each column:", col_max, sep = "\n")

# Min element in each row
row_min = a.min(axis = 1)
print("Min in each row:", row_min, sep = "\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Max:
9
Min:
1
Max in each column:
[7 8 9]
Min in each row:
[1 5 9]


### **QUESTION 19**
>Given an array `arr` of any shape, which of the following expressions returns the mean of `arr`, assuming there's no error?
<ol type='A'>
    <li><code>np.mean(arr)</code></li>
    <li><code>arr.mean()</code></li>
    <li><code>arr.sum() / arr.size</code></li>
    <li>All of the above</li>
</ol>

In [ ]:
# Answer: D


### **QUESTION 20**
>Given an array `arr` of any shape, which of the following expressions returns the standard deviation of `arr`, assuming there's no error?
<ol type='A'>
    <li><code>arr.std()</code></li>
    <li><code>arr.var()**(1/2)</code></li>
    <li><code>np.sqrt(np.var(arr))</code></li>
    <li><code>np.std(arr)</code></li>
    <li><code>np.sqrt((arr**2).mean() - arr.mean()**2)</code></li>
    <li>All of the above</li>
 </ol>

In [ ]:
# Answer: F
